main: "cc.dreamcode.kits.DreamKits"
version: "1.0-InDEV"
name: "Dream-Kits"
description: "Dream-Kits plugin written by dreamcode.cc"
website: "https://dreamcode.cc"
author: "Muszek_"
api-version: 1.13